# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, ManualWorkflow ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test_from_python38:
    # On python 3.8 and higher, all our Django versions are supported.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test with tox
        run: |
          poetry run tox -e 38support

  test_on_python37:
    # On python 3.7, Django 4.2 is not supported.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7',]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test with tox
        run: |
          poetry run tox -e 37support
